{
  Headline: {
    EffectiveDate: '2020-01-15T19:00:00+08:00',
    EffectiveEpochDate: 1579086000,
    Severity: 7,
    Text: '星期三夜间温和',
    Category: 'heat',
    EndDate: '2020-01-16T07:00:00+08:00',
    EndEpochDate: 1579129200,
    MobileLink: 'http://m.accuweather.com/zh/cn/shenzhen/58194/extended-weather-forecast/58194?unit=c&lang=zh-cn',
    Link: 'http://www.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?unit=c&lang=zh-cn',
  },
  DailyForecasts: [
    {
      Date: '2020-01-13T07:00:00+08:00',
      EpochDate: 1578870000,
      Sun: { Rise: '2020-01-13T07:06:00+08:00', EpochRise: 1578870360, Set: '2020-01-13T17:58:00+08:00', EpochSet: 1578909480 },
      Moon: {
        Rise: '2020-01-13T20:38:00+08:00',
        EpochRise: 1578919080,
        Set: '2020-01-14T09:55:00+08:00',
        EpochSet: 1578966900,
        Phase: 'WaningGibbous',
        Age: 18,
      },
      Temperature: { Minimum: { Value: 15.0, Unit: 'C', UnitType: 17 }, Maximum: { Value: 21.0, Unit: 'C', UnitType: 17 } },
      RealFeelTemperature: { Minimum: { Value: 14.3, Unit: 'C', UnitType: 17 }, Maximum: { Value: 20.8, Unit: 'C', UnitType: 17 } },
      RealFeelTemperatureShade: { Minimum: { Value: 14.3, Unit: 'C', UnitType: 17 }, Maximum: { Value: 19.4, Unit: 'C', UnitType: 17 } },
      HoursOfSun: 5.4,
      DegreeDaySummary: { Heating: { Value: 0.0, Unit: 'C', UnitType: 17 }, Cooling: { Value: 0.0, Unit: 'C', UnitType: 17 } },
      AirAndPollen: [
        { Name: 'AirQuality', Value: 46, Category: '良好', CategoryValue: 1, Type: '臭氧' },
        { Name: 'Grass', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Mold', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Ragweed', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Tree', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'UVIndex', Value: 4, Category: '中度', CategoryValue: 2 },
      ],
      Day: {
        Icon: 4,
        IconPhrase: '间歇性多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '大部分多云',
        LongPhrase: '大部分多云',
        PrecipitationProbability: 25,
        ThunderstormProbability: 0,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 14.8, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 65, Localized: '东北偏东', English: 'ENE' } },
        WindGust: { Speed: { Value: 22.2, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 69, Localized: '东北偏东', English: 'ENE' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 55,
      },
      Night: {
        Icon: 35,
        IconPhrase: '部分多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '部分多云',
        LongPhrase: '部分多云',
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 9.3, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 104, Localized: '东南偏东', English: 'ESE' } },
        WindGust: { Speed: { Value: 13.0, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 99, Localized: '东', English: 'E' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 4,
      },
      Sources: ['中国天气通'],
      MobileLink: 'http://m.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=1&unit=c&lang=zh-cn',
      Link: 'http://www.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=1&unit=c&lang=zh-cn',
    },
    {
      Date: '2020-01-14T07:00:00+08:00',
      EpochDate: 1578956400,
      Sun: { Rise: '2020-01-14T07:06:00+08:00', EpochRise: 1578956760, Set: '2020-01-14T17:59:00+08:00', EpochSet: 1578995940 },
      Moon: {
        Rise: '2020-01-14T21:42:00+08:00',
        EpochRise: 1579009320,
        Set: '2020-01-15T10:39:00+08:00',
        EpochSet: 1579055940,
        Phase: 'WaningGibbous',
        Age: 19,
      },
      Temperature: { Minimum: { Value: 15.0, Unit: 'C', UnitType: 17 }, Maximum: { Value: 22.0, Unit: 'C', UnitType: 17 } },
      RealFeelTemperature: { Minimum: { Value: 13.5, Unit: 'C', UnitType: 17 }, Maximum: { Value: 23.5, Unit: 'C', UnitType: 17 } },
      RealFeelTemperatureShade: { Minimum: { Value: 13.5, Unit: 'C', UnitType: 17 }, Maximum: { Value: 20.7, Unit: 'C', UnitType: 17 } },
      HoursOfSun: 10.7,
      DegreeDaySummary: { Heating: { Value: 0.0, Unit: 'C', UnitType: 17 }, Cooling: { Value: 0.0, Unit: 'C', UnitType: 17 } },
      AirAndPollen: [
        { Name: 'AirQuality', Value: 94, Category: '中度', CategoryValue: 2, Type: '臭氧' },
        { Name: 'Grass', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Mold', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Ragweed', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Tree', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'UVIndex', Value: 5, Category: '中度', CategoryValue: 2 },
      ],
      Day: {
        Icon: 3,
        IconPhrase: '部分晴',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '部分晴，天气宜人',
        LongPhrase: '部分晴，天气宜人',
        PrecipitationProbability: 5,
        ThunderstormProbability: 0,
        RainProbability: 5,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 11.1, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 117, Localized: '东南偏东', English: 'ESE' } },
        WindGust: { Speed: { Value: 14.8, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 110, Localized: '东南偏东', English: 'ESE' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 2,
      },
      Night: {
        Icon: 35,
        IconPhrase: '部分多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '部分多云',
        LongPhrase: '部分多云',
        PrecipitationProbability: 4,
        ThunderstormProbability: 0,
        RainProbability: 4,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 11.1, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 106, Localized: '东南偏东', English: 'ESE' } },
        WindGust: { Speed: { Value: 16.7, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 92, Localized: '东', English: 'E' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 29,
      },
      Sources: ['中国天气通'],
      MobileLink: 'http://m.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=2&unit=c&lang=zh-cn',
      Link: 'http://www.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=2&unit=c&lang=zh-cn',
    },
    {
      Date: '2020-01-15T07:00:00+08:00',
      EpochDate: 1579042800,
      Sun: { Rise: '2020-01-15T07:06:00+08:00', EpochRise: 1579043160, Set: '2020-01-15T18:00:00+08:00', EpochSet: 1579082400 },
      Moon: {
        Rise: '2020-01-15T22:44:00+08:00',
        EpochRise: 1579099440,
        Set: '2020-01-16T11:20:00+08:00',
        EpochSet: 1579144800,
        Phase: 'WaningGibbous',
        Age: 20,
      },
      Temperature: { Minimum: { Value: 16.0, Unit: 'C', UnitType: 17 }, Maximum: { Value: 22.0, Unit: 'C', UnitType: 17 } },
      RealFeelTemperature: { Minimum: { Value: 14.9, Unit: 'C', UnitType: 17 }, Maximum: { Value: 22.7, Unit: 'C', UnitType: 17 } },
      RealFeelTemperatureShade: { Minimum: { Value: 14.9, Unit: 'C', UnitType: 17 }, Maximum: { Value: 20.5, Unit: 'C', UnitType: 17 } },
      HoursOfSun: 5.3,
      DegreeDaySummary: { Heating: { Value: 0.0, Unit: 'C', UnitType: 17 }, Cooling: { Value: 1.0, Unit: 'C', UnitType: 17 } },
      AirAndPollen: [
        { Name: 'AirQuality', Value: 29, Category: '良好', CategoryValue: 1, Type: '臭氧' },
        { Name: 'Grass', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Mold', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Ragweed', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Tree', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'UVIndex', Value: 5, Category: '中度', CategoryValue: 2 },
      ],
      Day: {
        Icon: 4,
        IconPhrase: '间歇性多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '部分晴，天气宜人',
        LongPhrase: '部分晴，天气宜人',
        PrecipitationProbability: 4,
        ThunderstormProbability: 0,
        RainProbability: 4,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 13.0, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 101, Localized: '东', English: 'E' } },
        WindGust: { Speed: { Value: 18.5, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 110, Localized: '东南偏东', English: 'ESE' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 54,
      },
      Night: {
        Icon: 35,
        IconPhrase: '部分多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '部分多云',
        LongPhrase: '部分多云',
        PrecipitationProbability: 25,
        ThunderstormProbability: 0,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 11.1, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 100, Localized: '东', English: 'E' } },
        WindGust: { Speed: { Value: 16.7, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 101, Localized: '东', English: 'E' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 77,
      },
      Sources: ['中国天气通'],
      MobileLink: 'http://m.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=3&unit=c&lang=zh-cn',
      Link: 'http://www.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=3&unit=c&lang=zh-cn',
    },
    {
      Date: '2020-01-16T07:00:00+08:00',
      EpochDate: 1579129200,
      Sun: { Rise: '2020-01-16T07:06:00+08:00', EpochRise: 1579129560, Set: '2020-01-16T18:01:00+08:00', EpochSet: 1579168860 },
      Moon: {
        Rise: '2020-01-16T23:44:00+08:00',
        EpochRise: 1579189440,
        Set: '2020-01-17T12:00:00+08:00',
        EpochSet: 1579233600,
        Phase: 'WaningGibbous',
        Age: 21,
      },
      Temperature: { Minimum: { Value: 15.0, Unit: 'C', UnitType: 17 }, Maximum: { Value: 23.0, Unit: 'C', UnitType: 17 } },
      RealFeelTemperature: { Minimum: { Value: 14.5, Unit: 'C', UnitType: 17 }, Maximum: { Value: 25.4, Unit: 'C', UnitType: 17 } },
      RealFeelTemperatureShade: { Minimum: { Value: 14.5, Unit: 'C', UnitType: 17 }, Maximum: { Value: 22.4, Unit: 'C', UnitType: 17 } },
      HoursOfSun: 6.1,
      DegreeDaySummary: { Heating: { Value: 0.0, Unit: 'C', UnitType: 17 }, Cooling: { Value: 1.0, Unit: 'C', UnitType: 17 } },
      AirAndPollen: [
        { Name: 'AirQuality', Value: 19, Category: '良好', CategoryValue: 1, Type: '臭氧' },
        { Name: 'Grass', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Mold', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Ragweed', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Tree', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'UVIndex', Value: 5, Category: '中度', CategoryValue: 2 },
      ],
      Day: {
        Icon: 3,
        IconPhrase: '部分晴',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '部分晴，天气宜人',
        LongPhrase: '部分晴，天气宜人',
        PrecipitationProbability: 25,
        ThunderstormProbability: 20,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 7.4, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 131, Localized: '东南', English: 'SE' } },
        WindGust: { Speed: { Value: 13.0, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 91, Localized: '东', English: 'E' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 48,
      },
      Night: {
        Icon: 38,
        IconPhrase: '大部分多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '大部分多云',
        LongPhrase: '大部分多云',
        PrecipitationProbability: 25,
        ThunderstormProbability: 20,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 9.3, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 81, Localized: '东', English: 'E' } },
        WindGust: { Speed: { Value: 14.8, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 41, Localized: '东北', English: 'NE' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 86,
      },
      Sources: ['中国天气通'],
      MobileLink: 'http://m.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=4&unit=c&lang=zh-cn',
      Link: 'http://www.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=4&unit=c&lang=zh-cn',
    },
    {
      Date: '2020-01-17T07:00:00+08:00',
      EpochDate: 1579215600,
      Sun: { Rise: '2020-01-17T07:06:00+08:00', EpochRise: 1579215960, Set: '2020-01-17T18:01:00+08:00', EpochSet: 1579255260 },
      Moon: { Rise: null, EpochRise: null, Set: '2020-01-17T12:00:00+08:00', EpochSet: 1579233600, Phase: 'Last', Age: 22 },
      Temperature: { Minimum: { Value: 15.0, Unit: 'C', UnitType: 17 }, Maximum: { Value: 21.0, Unit: 'C', UnitType: 17 } },
      RealFeelTemperature: { Minimum: { Value: 14.4, Unit: 'C', UnitType: 17 }, Maximum: { Value: 22.0, Unit: 'C', UnitType: 17 } },
      RealFeelTemperatureShade: { Minimum: { Value: 14.4, Unit: 'C', UnitType: 17 }, Maximum: { Value: 19.6, Unit: 'C', UnitType: 17 } },
      HoursOfSun: 3.8,
      DegreeDaySummary: { Heating: { Value: 0.0, Unit: 'C', UnitType: 17 }, Cooling: { Value: 0.0, Unit: 'C', UnitType: 17 } },
      AirAndPollen: [
        { Name: 'AirQuality', Value: 32, Category: '良好', CategoryValue: 1, Type: '臭氧' },
        { Name: 'Grass', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Mold', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Ragweed', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'Tree', Value: 0, Category: '低', CategoryValue: 1 },
        { Name: 'UVIndex', Value: 3, Category: '中度', CategoryValue: 2 },
      ],
      Day: {
        Icon: 4,
        IconPhrase: '间歇性多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '01' },
        ShortPhrase: '部分晴',
        LongPhrase: '部分晴',
        PrecipitationProbability: 9,
        ThunderstormProbability: 0,
        RainProbability: 9,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 11.1, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 40, Localized: '东北', English: 'NE' } },
        WindGust: { Speed: { Value: 16.7, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 36, Localized: '东北', English: 'NE' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 70,
      },
      Night: {
        Icon: 7,
        IconPhrase: '多云',
        HasPrecipitation: false,
        LocalSource: { Id: 7, Name: 'Huafeng', WeatherCode: '02' },
        ShortPhrase: '多云',
        LongPhrase: '多云',
        PrecipitationProbability: 5,
        ThunderstormProbability: 0,
        RainProbability: 5,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: { Speed: { Value: 9.3, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 52, Localized: '东北', English: 'NE' } },
        WindGust: { Speed: { Value: 13.0, Unit: 'km/h', UnitType: 7 }, Direction: { Degrees: 45, Localized: '东北', English: 'NE' } },
        TotalLiquid: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Rain: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        Snow: { Value: 0.0, Unit: 'cm', UnitType: 4 },
        Ice: { Value: 0.0, Unit: 'mm', UnitType: 3 },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 19,
      },
      Sources: ['中国天气通'],
      MobileLink: 'http://m.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=5&unit=c&lang=zh-cn',
      Link: 'http://www.accuweather.com/zh/cn/shenzhen/58194/daily-weather-forecast/58194?day=5&unit=c&lang=zh-cn',
    },
  ],
}
